<a href="https://colab.research.google.com/github/Ramadane735/CSS-AVANC-E/blob/main/classe_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# if statement

val = input("Enter the number")
#value inputted using input() function is in string data type. so, we need typecasting
value_float = float(val)
if(value_float > 100):
    print("greater than hunderd")

Enter the number105
greater than hunderd


In [ ]:
value = int(input("Enter the no"))
if(value % 2 == 0):
    print("even")
else:
    print("odd")

Enter the no2
even


In [ ]:
# Age form
age = float(input("Enter your age: "))
if(age<18):
    print("You are not eligible to vote")
else:
    print("Eligible to vote")

Enter your age: 22
Eligible to vote


In [ ]:
# if-elif-else
# Age form
age = float(input("Enter your age: "))
if(age<18):
    print("Minor Age")
elif(age >= 18 and age<= 45):
    print("Mid-Age")
elif(age>45 and age<= 60):
    print("Senior Mid Age")
else:
    print("Senior Citizen")

Enter your age: 65
Senior Citizen


In [ ]:
# nested if else
age = float(input("Enter your age: "))
if(age<18):
    if(age<15):
        print("You are in school, Minor age")
    else:
        print("You are in college, Minor age")
elif(age >= 18 and age<= 45):
    print("Mid-Age")
elif(age>45 and age<= 60):
    print("Senior Mid Age")
else:
    print("Senior Citizen")

Enter your age: 15
You are in college, Minor age


In [ ]:
# Loop statements

In [ ]:
#for loop
lst = [1,2,3,4,5]
for i in lst:
    print (i)

1
2
3
4
5


In [ ]:
lst = [1,2,3,4,5]
for i in lst:
    print (i*i)

1
4
9
16
25


In [ ]:
# find the sum of all the elements in the list
list = [1,2,3,4,5,6,7,8,9,10]
sum1 = 0
for i in list:
    sum1+=i
print(sum1)

55


In [ ]:
# find the sum of even and odd number
list1 = [1,2,3,4,5,6,7,8,9,10]
even_sum = 0
odd_sum = 0
for i in list1:
    if(i%2 == 0):
        even_sum += i
    else:
        odd_sum += i
print("Even sum is {} and odd sum is {}". format(even_sum, odd_sum))

Even sum is 30 and odd sum is 25


In [ ]:
# while loops
i = 0
while(i<=10):
    print(i)
    i = i+1

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
# break
x = 1
while(x<7):
    print(x)
    if(x == 4):
        break
    x=x+1

1
2
3
4


In [ ]:
# continue
x = 0
while x<7:
    x = x+1
    if x==4:
        continue
    print(x)

1
2
3
5
6
7


In [ ]:
# printing even numbers
for i in range(1,50):
    if(i % 2 == 0):
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48


In [ ]:
# factorial calculation
fact = 1
n = int(input("Enter the number"))
i = n
while(i != 0):
    fact = fact*i
    i = i-1
print(fact)

Enter the number5
120


In [ ]:
#Python program that asks the user for a positive integer and then calculates the sum of all numbers from 1 to that integer using a for loop.
num = int(input("Enter the number"))
sum1 = 0
for i in range(1, num+1):
    sum1 += i
print("Sum is {}".format(sum1))

Enter the number5
Sum is 15


In [ ]:
# Fibanacci sequence
n = int(input("How many terms of fibonacci series you want to print?"))
a=0
b=1
print(a)
print(b)
for i in range(n-1):
    c= a+b
    print(c)
    a=b
    b = c



How many terms of fibonacci series you want to print?10
0
1
1
2
3
5
8
13
21
34
55


In [ ]:
#  Python program to print the multiplication table of a given number using a nested for loop.
num = int(input("Enter the number: "))
for i in range(10):
    print("{} * {} = {}".format(num,i+1, num*(i+1)))

Enter the number: 12
12 * 1 = 12
12 * 2 = 24
12 * 3 = 36
12 * 4 = 48
12 * 5 = 60
12 * 6 = 72
12 * 7 = 84
12 * 8 = 96
12 * 9 = 108
12 * 10 = 120


In [ ]:
# pattern printing
for i in range(6):
    for j in range(i):
        print("*", end=" ")
    print("\n")




* 

* * 

* * * 

* * * * 

* * * * * 



In [ ]:
for i in range(5,0,-1):
    for j in range(i):
        print("*", end=" ")
    print("\n")

* * * * * 

* * * * 

* * * 

* * 

* 



In [ ]:
for i in range(1, 6):
    print(" "*(5-i)+ "*"*i)

    *
   **
  ***
 ****
*****


operation


In [ ]:
a=7
b=9
print(a+b)

16


In [ ]:
a=7
b=9
print(a/b),a/b

0.7777777777777778


(None, 0.7777777777777778)

#Types de donnee

In [ ]:
#intiger (entier)
x=10
type(x)

int

In [ ]:
#float (decimal)
x=4,6
print(type(x))

<class 'tuple'>


In [ ]:
#string(chaine)
nom="maria"
print(type(nom))

<class 'str'>


In [ ]:
x=True
print(type(x))

<class 'bool'>


In [ ]:
x=12
y=10
print(x<y)

False


In [ ]:
x=12
y=10
print(x>y)

True


#Indexing et slicing en python

In [ ]:
#indexing en python
samedi="bonjour classe"
print("samedi[0]=",samedi[0])

samedi[0]= b


In [ ]:
samedi="bonjour classe"
print("samedi[1]=",samedi[1])

samedi[1]= o


In [ ]:
samedi="bonjour classe"
print("samedi[-1]=",samedi[-1])

samedi[-1]= e


In [ ]:
#slicing
print("samedi[0:3]=", samedi[0:3])


samedi[0:3]= bon


In [ ]:
print("samedi[0:4]=", samedi[0:4])

samedi[0:4]= bonj


In [ ]:
print("samedi[1:5]=", samedi[1:5])

samedi[1:5]= onjo


In [ ]:
#concatenation de deux ou plusieurs chaines
ch1="c'est notre premier seance "
ch2="de cours a GOMYCODE"

resultat=ch1+ch2
print("ch1+ch2", resultat)

ch1+ch2 c'est notre premier seance de cours a GOMYCODE


In [ ]:
#la longueur d'une chaine
print(len(resultat))

46


In [ ]:
resultat[a]

'o'

In [ ]:
x=10
type(x)

int

In [ ]:
float(x)

10.0

In [ ]:
str(x)

'10'

#exercice

In [ ]:
#un programme qui demande a l'utilisateur de deviner un nombre


nombre_secret=7         #le nombre a deviner
essai=None              #Initialisation de la variable

while essai != nombre_secret: # Tant que l'utilisateur n'a devine
   essai= int(input("devinez le nombre : ")) # Demande une saisie
   if essai < nombre_secret:
     print("Trop petit !")
   elif essai > nombre_secret:
     print("Trop grand !")
print("Bravo, vous avez trouve le nombre !")

devinez le nombre : 5
Trop petit !
devinez le nombre : 8
Trop grand !
devinez le nombre : 7
Bravo, vous avez trouve le nombre !


In [ ]:
#La fonction enumarate() permet de parcourir une sequence tout en ayant acces a l'indice de chaque element


chaine="Bonjour classe"

for i,lettre in enumerate(chaine):  # on dit a l'assistant de nous donner ces deux choses(l'indice et la lettre) a chaque fois
   print(f"Index {i} :'{lettre}' ")

Index 0 :'B' 
Index 1 :'o' 
Index 2 :'n' 
Index 3 :'j' 
Index 4 :'o' 
Index 5 :'u' 
Index 6 :'r' 
Index 7 :' ' 
Index 8 :'c' 
Index 9 :'l' 
Index 10 :'a' 
Index 11 :'s' 
Index 12 :'s' 
Index 13 :'e' 


#**Data structures/ Structures de donnees**

Une structure de donnees(data structure) en python est une facon d'organiser et de stocker les donnees pour pouvoir les utiliser efficacement

#**Liste(list) Collection ordonnee et modifiable d'elements [ ]**

In [ ]:
liste1=[]    #liste vide

In [ ]:
liste2=[2,3,7]   #liste d'entier

In [ ]:
liste3=["Dakar","Fouta","ziguinchor","Kolda","Saint-Louis"]  #liste chaine de caractere

In [ ]:
liste4=[3,"Abib",5.4,True]   #liste mixte

In [ ]:
liste5=[liste2,liste3,liste4]  #Nested list: une liste qui contient d'autres listes
print('liste5',liste5)

liste5 [[2, 3, 7], ['Dakar', 'Fouta', 'ziguinchor', 'Kolda', 'Saint-Louis'], [3, 'Abib', 5.4, True]]


In [ ]:
#List comprehension:c'est mettre une boucle for dans une list

liste_a=[i**2 for i in range(10)]
print(liste_a)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
for i in range(11):
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
#l'indexation/ INDEXING
Samedi=[1,45,9,7,3]

In [ ]:
print(Samedi[1])  #acceder au 2eme element de notre liste: on utilise l'indexe 1

45


In [ ]:
print(Samedi[-1])

3


In [ ]:
#Trancher/ SLICING
print(Samedi[0:4])

[1, 45, 9, 7]


In [ ]:
print(Samedi[2:])

[9, 7, 3]


In [ ]:
#TRIER une liste
Samedi=[1,45,9,7,3]
Samedi.sort()
print(Samedi) #dans l'ordre croissant

[1, 3, 7, 9, 45]


In [ ]:
Samedi.sort(reverse=True)
print(Samedi) #dans l'ordre decroissant

[45, 9, 7, 3, 1]


In [ ]:
# Ajouter un element a notre liste
Samedi.append(15)
print(Samedi)

[45, 9, 7, 3, 1, 15]


In [ ]:
#Pour supprimer
Samedi.remove(45)
print(Samedi)

[9, 7, 3, 1, 15]


In [ ]:
#ajouter un element en indiquant l'index
Samedi.insert(2,11)
Samedi

[9, 7, 11, 3, 1, 15]

In [ ]:
#modifier la valeur de l'index
Samedi[0]=2
print(Samedi)

[2, 7, 11, 3, 1, 15]


In [ ]:
#Supprimer un index specifique
del Samedi[4]
print(Samedi)

[2, 7, 11, 3, 15]


In [ ]:
#longueur
len(Samedi)

5

#**Dictionnaire(dict) Collection non ordonnee de paires cle-valeur{ }**

In [ ]:
#comment creer un dictionnaire
etudiant={"Nom":"Mouhamed","Age":18,"Note":15}
print('etudiant:',etudiant)

etudiant: {'Nom': 'Mouhamed', 'Age': 18, 'Note': 15}


etudiant={'Nom':["Mouhamed","Awa","Moussa"],
          'Age':[23,43,24],
          'Note':[15,16,19]}
etudiant

In [ ]:
#parcourir aux elements de notre dictionnaire

#keys
for key in etudiant.keys():
  print(key)

Nom
Age
Note


In [ ]:
#values
for value in etudiant.values():
  print(value)

['Mouhamed', 'Awa', 'Moussa']
[23, 43, 24]
[15, 16, 19]


In [ ]:
for item in etudiant.items():
  print(item)

('Nom', ['Mouhamed', 'Awa', 'Moussa'])
('Age', [23, 43, 24])
('Note', [15, 16, 19])


In [ ]:
#Longueur
print(len(etudiant))

3


In [ ]:
#ajouter un element
etudiant["taille"]=1.75
etudiant

{'Nom': ['Mouhamed', 'Awa', 'Moussa'],
 'Age': [23, 43, 24],
 'Note': [15, 16, 19],
 'taille': 1.75}

In [ ]:
#supprimer un element
etudiant.pop("Note")
etudiant

{'Nom': ['Mouhamed', 'Awa', 'Moussa'], 'Age': [23, 43, 24], 'taille': 1.75}

#**FONCTION**

Qu'est-ce qu'une fonction ?

En Python, une fonction est un bloc de code reutilisable qui effectue une tache specifique. C'est comme une mini-recette que vous pouvez utiliser encore et encore, sans avoir a reecrire toutes les instructions

In [ ]:
A=[2,4,6,7,8]
#Longueur de la liste
len(A)

5

**#FONCTION SANS PARAMETRE**

In [ ]:
def saluer():
    print("Bonjour la classe")

In [ ]:
saluer() #appeler la foction

Bonjour la classe


**#Fonction avec un seul parametre**

In [ ]:
#Creer ene fonction signe qui permettra de connaitre le signe d'un nombre

def signe(x):
  #instructions
  if x > 0:
    print("le nombre est positif")

  elif x == 0:
    print("le nombre est nul")

  else:
    print("le nombre est negatif")

In [ ]:
signe(-5)

le nombre est negatif


In [ ]:
signe(4)

le nombre est positif


In [ ]:
signe(0)

le nombre est nul


**#Fonction a parametre multiples**

In [ ]:
#Argument: valeur envoyee a la fonction lors de son appel
#parametre: la variable repertoriee entre parentheses dans la definition de la fonction

def addition(a,b):
    somme=a+b
    print('somme:',somme)

In [ ]:
addition(4,6)  #4 et 6 sont des arguments

somme: 10


In [ ]:
def multiplication(a,b,c):
    produit=(a+b)*(c)
    print('produit:',produit)

In [ ]:
multiplication(10,7,3)

produit: 31


In [ ]:
def prod(a,b,c):
    prod=a*b*c
    print('prod:',prod)

In [ ]:
prod(4,7,9)

prod: 252


**#La declaration de retour**

Dans une fonction, return est utilise pour envoyer une valeure apres l'execution du code. cela permet d'utiliser le resultat de la fonction ailleurs dans le programme

In [ ]:
def double(nombre):
  return nombre*2  #La fonction renvoie le double du nombre

In [ ]:
resultat=double(5)
print(resultat)

10


In [ ]:
def addition(a,b):
    return a+b  #Retourne la somme des deux nombres

In [ ]:
# exemple d'utilisation
resultat=addition(5,9)
print(resultat)

14


In [ ]:
#Argument par defaut
def calculer_aire(longueur, largeur=1):
  return longueur*largeur

In [ ]:
aire=calculer_aire(5)
print(aire)

5


**#Fonction lambda**

une fonction lambda est une fonction anonyme definie en une seule ligne. Elle est souvent utilisee pour les calculs simples et rapides

In [ ]:
f= lambda x:x**2+2*x+4

f(2)

In [ ]:
f= lambda x,y:4*x+5*y

In [ ]:
f(2,5)

33

**#Fontion map()**

La fonction map() est une fonction integree en python qui applique une fonction a chaque element d'une interable(comme une liste ou un tuple) et retourne un nouvel iterable avec les resultats.

In [ ]:
#la syntaxe
##map(fonction,interable)
#1. fonction:la fonction a apppliquer a chaque element
#2. iterable:la liste, le tuple ou un autre sur lequel la fonction sera appliquee

In [ ]:
#Liste de nombres
nombres=[1,2,3,4,5]

#Fonction lambda pour doubler un nombre
double=map(lambda x:2*x,nombres)

#COnvertir le resultat en liste

print(list(double))


[2, 4, 6, 8, 10]


#**Polymorphisme**


Le polymorphisme est un concepte de la POO qui permet d'utiliser une meme methode sur des objets de classe differentes; tout en ayant un comportement adapte a chaque classe. En d'autres termes, une methode peut avoir differentes implementations selon l'objet sur lequel elle est appelee.

#**Exemple**

on va creer une classe animal avec une methode faire_son(). Ensuite, on va creer des classes chien et chat, qui heriterons d'Animal, mais avec leur propre version de faire_son()

In [3]:
#classe parent
class Animal:
  def faire_son(self):
    pass        #Methode generique a redefinir
#classe enfant 1
class chien(Animal):
  def faire_son(self):
    return "wouf wouf"  #le chien aboie

#classe enfant 2
class chat(Animal):
  def faire_son(self):
    return "Miaou Miaou"

#utilisation du polymorphisme
animaux=[chien(), chat()]   #Liste contenant des objets de differentes classes

for animal in animaux:
  print(animal.faire_son())

wouf wouf
Miaou Miaou


#**Numpy**

Numpy(***Numerical Python***) est un bibliotheque specialise dans le calcul numerique et la manupilation de tableau de donnees(appeles Arrays).

Elle permet de faire des calculs mathematiques rapides et efficaces sur des grands ensembles de donnees, bien plus rapidement qu'avec les listes Python classiques.

In [ ]:
import numpy as np


#**1 Creation de tableau**

In [5]:
#comment creer un tableau 1D
import numpy as np
A=np.array([1,7,8])
A

array([1, 7, 8])

In [7]:
#comment creer un tableau 2D
B=np.array([[1,2,3],[4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [8]:
C=np.array([[2,4,5],[1,3,8],[5,8,9]])
print(C)

[[2 4 5]
 [1 3 8]
 [5 8 9]]


In [9]:
#nombre de dimension
C.ndim

2

In [10]:
#la forme de notre tableau
C.shape

(3, 3)

In [11]:
#tableau qui contient que des 0
M=np.zeros((3,2))
print(M)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
#tableau qui contient que des 1
N=np.ones((3,4))
print(N)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# remplir un tableau avec le mm nombre
E=np.full((3,4),9)
E

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [21]:
# Tableau avec des nombres aleatoire
A=np.random.randn(3,4)   #nombres aleatoires qui suivent la distribution normale centres en 0
print(A)

[[ 2.26975462 -1.45436567  0.04575852 -0.18718385]
 [ 1.53277921  1.46935877  0.15494743  0.37816252]
 [-0.88778575 -1.98079647 -0.34791215  0.15634897]]


In [19]:
A=np.random.seed(0) # c'est pour fixer le nombre
A=np.random.randn(3,4)
print(A)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]


In [26]:
#tableau qui contient un debut, un fin et une quantite
G=np.linspace(0,10,20)
print(G)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [27]:
# tableau qui a un debut, un fin et un pas
I=np.arange(0,10,0.5)
print(I)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


# Manupilation de tableau

In [32]:
B=np.ones((3,2))
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
A=np.zeros((3,2))
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [33]:
# Assembler les tableaux
np.hstack((A,B))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [34]:
np.vstack((A,B))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
# Concatener: Concatener c'est a dire combiner des tableaux le long d'un axe donne
np.concatenate((A,B),axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
np.concatenate((A,B),axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [37]:
J=np.concatenate((A,B),axis=0)
print(J)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [38]:
J.reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

# a Indexng

In [39]:
I=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(I)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
#Acceder aux elements de notre tableau
I[0,0]   # premiere ligne premiere colonne

np.int64(1)

In [42]:
I[0,1]

np.int64(2)

# **Silicing**

In [43]:
print(I)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# Tous les elements de la premiere colonne
I[:,0]


array([1, 4, 7])

In [46]:
# tous les elements de la premiere ligne
I[0,:]

array([1, 2, 3])

In [47]:
I[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [48]:
H=np.zeros((4,4))
print(H)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [52]:
H[1:3,1:3]=1
print(H)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [55]:
H[2:,2:]=2
print(H)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 2. 2.]
 [0. 0. 2. 2.]]


#** Mathematiques et Statistiques**

In [56]:
import numpy as np
A=np.random.seed(0)
A=np.random.randint(0,10,[2,3])
print(A)

[[5 0 3]
 [3 7 9]]


In [57]:
# Somme de tous les elements
A.sum()

np.int64(27)

In [58]:
# Somme au niveau des colonnes
A.sum(axis=0)

array([ 8,  7, 12])

In [59]:
# produit
A.prod()

np.int64(0)

In [60]:
# Maximum
A.max()

np.int64(9)

In [61]:
# Minimum
A.min()

np.int64(0)

In [62]:
# Moyenne
A.mean()

np.float64(4.5)

In [63]:
# Variance
A.var()

np.float64(8.583333333333334)

In [64]:
# Ecart-type
A.std()

np.float64(2.9297326385411577)

In [65]:
from ast import Index
# index de la valeur minimale
Index_valeurmin=np.argmin(A)
print((Index_valeurmin))

1
